### ISSUE TITLE
Datový model pro jízdní řády

### ISSUE THREAD

**Issue by FireGamesCZ** [sps-trutnov-eps/projekt-4ep-pruvodce#11]
Vytvořit datový model pro jízdní řády:
Návrh:
Číslo spoje
Zastávky - Ideálně nová class, kde je u každé zastávky rovnou i čas + IREDO tarifní zóna
Typ dopravy MHD/Příměstský autobus/Dálkový autobus/vlak

**Comment by CrazyCatCZ** [comment]
Takže chceš udělat ještě další model Zastávka?

**Comment by FireGamesCZ** [comment]
Přesnou implementaci nechám na vás, klidně může být.
