### ISSUE TITLE
Ověření emailu registrace

### ISSUE THREAD

**Issue by FireGamesCZ** [sps-trutnov-eps/projekt-4ep-pruvodce#21]
Bylo by ideální, kdyby byl uživatel po registraci přesměrován na stránku, která by chtěla kód a nemusel by otevírat odkaz v emailu. Odkaz v mailu bych stále ponechal jako alternativní možnost.

**Comment by Joucker29** [comment]
Osobně se mi link líbí více.

**Comment by AlesObr** [comment]
Za mě nadbytečné.
