### ISSUE TITLE
Po smazání účtu zůstane uživatel přihlášen

### ISSUE THREAD

**Issue by FireGamesCZ** [sps-trutnov-eps/projekt-4ep-pruvodce#22]
Když si uživatel maže účet, tak po ověření emailu, kde se odakz otevře v jiném prohližeči zůstává uživatel stále přihlášen.

**Comment by Joucker29** [comment]
hotfix

**Comment by vTekki** [comment]
ups

**Comment by AlesObr** [comment]
Asi opraveno
