### ISSUE TITLE
Otázka ohledně funkcionality ověřování přes email.

### ISSUE THREAD

**Issue by Joucker29** [sps-trutnov-eps/projekt-4ep-pruvodce#23]
Když se registrujete a pošlete si více ověřovacích kódů tak bude platit jen ten první. Tato funkcionalita platí všude kde se posílá ověřovací kód na email např:. mazání účtu, zapomněl jsem heslo, atd...
Mám tohle předělat aby platil jen ten poslední?

**Comment by FireGamesCZ** [comment]
Dle toho co jsem zkoušel tak platí pouze poslední vygenerovaný a ne ten první.
