### ISSUE TITLE
Špatná chybová hláška při pokusu se přihlásit bez ověřeného emailu

### ISSUE THREAD

**Issue by FireGamesCZ** [sps-trutnov-eps/projekt-4ep-pruvodce#24]
Když se uživatel snaží přihlásit na účet bez ověřeného emailu, ale se správným jménem a heslem, bylo by dobré, kdyby se uživateli neukázalo "Nesprávný e-mail nebo heslo!" ale například "Tento účet ještě nemá ověřený email" Popřípadě by byl uživatel přesměrován na stránku viz #21

**Comment by Joucker29** [comment]
Debatable. Já bych osobně řekl že jak to je udělané tak je to lepší protože vydáváme co nejméně informací.

**Comment by AlesObr** [comment]
Špatná hláška by působila zmatečně a akorát bychom riskovali, že nám někdo při pokusech o reset hesla přetíží server

**Comment by AlesObr** [comment]
@Vladyslav272 podíváš se na to?

**Comment by AlesObr** [comment]
@Vladyslav272 mohl by ses na to podívat? Díky!

**Comment by Vladyslav272** [comment]
Jo už nad tím zapracuji

Сб 21. 10. 2023 в 14:00, Aleš Obr ***@***.***>:

**Comment by Joucker29** [comment]
Nebudu opravovat kvůli bezpečnosti uživatelů.
