### ISSUE TITLE
Datový model pro učebnu

### ISSUE THREAD

**Issue by AlesObr** [sps-trutnov-eps/projekt-4ep-pruvodce#3]
Vytvoření datového modelu pro zobrazení třídy
Podrobnosti budou dořešeny v blízké budoucnosti

**Comment by AlesObr** [comment]
@Vladyslav272 budu potřebovat s tím trochu pohnout

**Comment by FireGamesCZ** [comment]
Info o učebně
cesta k fotkám - fotek může být pro 1 učebnu více

**Comment by kukavlk** [comment]
asi hotovo
