### ISSUE TITLE
Model pro crowd source

### ISSUE THREAD

**Issue by FireGamesCZ** [sps-trutnov-eps/projekt-4ep-pruvodce#34]
Bude obsahovat:
GUID
GUID uživatele co vytvořil
Nadpis
Text
Stav(čeká na vyřízení/schváleno/zamítnuto/již existuje)
Existujici (nepovinný, bokud je po ve Stavu již existuje bude zde GUID již existujícího reportu)

**Comment by Joucker29** [comment]
Tohle už je docela chvíli hotové.
