### ISSUE TITLE
Datový model budovy

### ISSUE THREAD

**Issue by AlesObr** [sps-trutnov-eps/projekt-4ep-pruvodce#4]
Datový model pro ukládání informací o budovách.
Předpoklad:
Adresa
Kódové označení (Š101, H618, H59, MB5/6
Učebny
(atd.)

**Comment by Vladyslav272** [comment]
ok

**Comment by FireGamesCZ** [comment]
Info
cesta k fotce

**Comment by FireGamesCZ** [comment]
Info obudově
cesta k fotkám - fotek může být pro 1 učebnu více
