### ISSUE TITLE
Render příspěvků

### ISSUE THREAD

**Issue by AlesObr** [sps-trutnov-eps/projekt-4ep-pruvodce#43]
Úprava příslušných controllerů a frontendu, aby bylo možné příspěvky správně renderovat, nejspíš bude nutná spolupráce s frontendem.
Část kódu, která by mohla být nápomocná (pro frontend) poskytnu na discord

**Comment by vTekki** [comment]
Bylo by skvělé vědět, jak vlastně ty příspěvky mají vypadat, kam se mají vypisovat a taky poskytnout slíbenou část kódu "která by mohla být nápomocná".
![Snímek obrazovky 2023-08-25 195048](https://github.com/sps-trutnov-eps/projekt-4ep-pruvodce/assets/81530407/fc62d60b-2dc5-4b35-b017-9c993e20453a)

**Comment by AlesObr** [comment]
Příspěvek = článek, z pohledu front-endu se jedná pouze o jeden div, do kterého se pak pomocí, již hotového, skriptu naparsuje již naformátovaný článek. Je tedy jenom potřeba, zatím, na stránce se stravovacími zařízeními pro to vytvořit jeden div (do kterého se článek bude vkládat), h2 na nadpis a <p> na datum vydání a to vše nějak šikovně umístit na příslušnou článku. Do budoucna se to pak bude řešit i na dalších stránkách

**Comment by vTekki** [comment]
Na příspěvky jsem udělal template v `Views > Shared > Prispevek_template.cshtml`.

Už stačí dodělat jen backend. 

![Snímek obrazovky 2023-07-29 184830](https://github.com/sps-trutnov-eps/projekt-4ep-pruvodce/assets/81530407/86c64d76-e801-4915-bc4c-d1c290f5ca08)
