### ISSUE TITLE
Nelze vytvářet migrace a update-database

### ISSUE THREAD

**Issue by FireGamesCZ** [sps-trutnov-eps/projekt-4ep-pruvodce#60]
Both Entity Framework 6 and Entity Framework Core are installed. The Entity Framework 6 tools are running. Use 'EntityFrameworkCore\Add-Migration' for Entity Framework Core.
No migrations configuration type was found in the assembly 'PruvodceProject'. (In Visual Studio you can use the Enable-Migrations command from Package Manager Console to add a migrations configuration).

![image](https://github.com/sps-trutnov-eps/projekt-4ep-pruvodce/assets/61122545/59796841-c2e3-48ad-aaaa-ed216ecc7684)

**Comment by CrazyCatCZ** [comment]
EntityFrameworkCore\Add-Migration
